version: "3"

services:
  mysql:
    container_name: mysql_container
    image: mysql:latest
    ports:
     - "3360:3306"
    volumes:
     - ./volumes/mysql/data:/var/lib/mysql
     - ./volumes/mysql/init:/docker-entrypoint-initdb.d/:ro
    environment:
     - MYSQL_ROOT_PASSWORD=root
  grafana:
    container_name: grafana_container
    image: grafana/grafana:6.5.0
    ports:
      - "3030:3000"
    user: '1000:1000'
    volumes:
      - ./volumes/grafana:/var/lib/grafana
      - ./volumes/grafana/init:/etc/grafana/provisioning
  node-red:
    container_name: nodered_container
    image: nodered/node-red:latest
    ports:
      - "1880:1880"
    volumes:
      - ./volumes/node-red:/data
  mosquitto:
    container_name: mosquitto_container
    image: eclipse-mosquitto
    ports:
      - "1883:1883"
    volumes:
      - "./volumes/mosquitto:/mosquitto"
